import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft, Download, Sparkles } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";

const CoverLetter = () => {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    jobTitle: "",
    companyName: "",
    hiringManager: "",
    jobDescription: "",
    yourExperience: "",
    whyInterested: "",
    keySkills: ""
  });
  const [generatedLetter, setGeneratedLetter] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);

  const handleInputChange = (field: string, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const generateCoverLetter = async () => {
    setIsGenerating(true);
    
    // Simulate AI generation (would use Google Cloud API in real implementation)
    setTimeout(() => {
      const letter = `
Dear ${formData.hiringManager || "Hiring Manager"},

I am writing to express my strong interest in the ${formData.jobTitle} position at ${formData.companyName}. With my background and passion for this field, I am excited about the opportunity to contribute to your team.

**Why I'm Interested:**
${formData.whyInterested || "I am drawn to this opportunity because of the company's reputation and the role's potential for growth."}

**My Relevant Experience:**
${formData.yourExperience || "I bring valuable experience and skills that align well with your requirements."}

**Key Skills I Bring:**
${formData.keySkills || "My key skills include strong analytical abilities, excellent communication, and a proactive approach to problem-solving."}

I am particularly excited about ${formData.companyName} because of its commitment to excellence and innovation. I believe my skills and enthusiasm make me an ideal candidate for this role.

I would welcome the opportunity to discuss how my experience and passion can contribute to your team's success. Thank you for considering my application.

Sincerely,
[Your Name]

---
*Generated by CareerNest AI Cover Letter Generator*
*Note: Full AI optimization available with Google Cloud API integration*
      `;
      
      setGeneratedLetter(letter);
      setIsGenerating(false);
      toast.success("Cover letter generated successfully!");
    }, 2000);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 via-yellow-50 to-red-50">
      {/* Header */}
      <header className="bg-white shadow-sm border-b">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center h-16">
            <Button variant="ghost" onClick={() => navigate("/dashboard")}>
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Dashboard
            </Button>
            <h1 className="text-xl font-semibold text-primary ml-4">AI Cover Letter Generator</h1>
          </div>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Input Form */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center">
                <Sparkles className="w-5 h-5 mr-2 text-primary" />
                Cover Letter Details
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <Label htmlFor="jobTitle">Job Title</Label>
                <Input
                  id="jobTitle"
                  value={formData.jobTitle}
                  onChange={(e) => handleInputChange("jobTitle", e.target.value)}
                  placeholder="e.g., Software Developer"
                />
              </div>
              
              <div>
                <Label htmlFor="companyName">Company Name</Label>
                <Input
                  id="companyName"
                  value={formData.companyName}
                  onChange={(e) => handleInputChange("companyName", e.target.value)}
                  placeholder="e.g., Tech Solutions Inc."
                />
              </div>
              
              <div>
                <Label htmlFor="hiringManager">Hiring Manager Name (Optional)</Label>
                <Input
                  id="hiringManager"
                  value={formData.hiringManager}
                  onChange={(e) => handleInputChange("hiringManager", e.target.value)}
                  placeholder="e.g., Ms. Sarah Johnson"
                />
              </div>
              
              <div>
                <Label htmlFor="jobDescription">Job Description/Requirements</Label>
                <Textarea
                  id="jobDescription"
                  value={formData.jobDescription}
                  onChange={(e) => handleInputChange("jobDescription", e.target.value)}
                  placeholder="Paste the job description or key requirements..."
                />
              </div>
              
              <div>
                <Label htmlFor="yourExperience">Your Relevant Experience</Label>
                <Textarea
                  id="yourExperience"
                  value={formData.yourExperience}
                  onChange={(e) => handleInputChange("yourExperience", e.target.value)}
                  placeholder="Describe your relevant experience..."
                />
              </div>
              
              <div>
                <Label htmlFor="whyInterested">Why You're Interested</Label>
                <Textarea
                  id="whyInterested"
                  value={formData.whyInterested}
                  onChange={(e) => handleInputChange("whyInterested", e.target.value)}
                  placeholder="Why do you want this role/company?"
                />
              </div>
              
              <div>
                <Label htmlFor="keySkills">Key Skills to Highlight</Label>
                <Textarea
                  id="keySkills"
                  value={formData.keySkills}
                  onChange={(e) => handleInputChange("keySkills", e.target.value)}
                  placeholder="List your most relevant skills..."
                />
              </div>

              <Button 
                onClick={generateCoverLetter} 
                className="w-full" 
                disabled={isGenerating}
              >
                {isGenerating ? "Generating..." : "Generate AI Cover Letter"}
              </Button>
            </CardContent>
          </Card>

          {/* Generated Cover Letter Preview */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center justify-between">
                <span>Generated Cover Letter</span>
                {generatedLetter && (
                  <Button variant="outline" size="sm">
                    <Download className="w-4 h-4 mr-2" />
                    Download
                  </Button>
                )}
              </CardTitle>
            </CardHeader>
            <CardContent>
              {generatedLetter ? (
                <div className="bg-white p-6 rounded border min-h-[600px]">
                  <pre className="whitespace-pre-wrap text-sm">{generatedLetter}</pre>
                </div>
              ) : (
                <div className="text-center text-muted-foreground py-12">
                  <Sparkles className="w-12 h-12 mx-auto mb-4 opacity-50" />
                  <p>Fill out the form and click "Generate" to see your personalized cover letter</p>
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  );
};

export default CoverLetter;